package com.hiddu.gym.enterprise.enums;

public enum GymPlanFrequencyEnum {
	GYM_ONE_TIME_REGISTRATION,
	GYM_PLAN_FREQUENCY_ONE_MONTH,
	GYM_PLAN_FREQUENCY_TWO_MONTHS,
	GYM_PLAN_FREQUENCY_QUERTLY,
	GYM_PLAN_FREQUENCY_HALF_YEARLY,
	GYM_PLAN_FREQUENCY_YEARLY
}
